const fullCardDeck = [
    //Clubs
    {
        name : "Two of Club",
        link : "./img/cardDeck/Club/2_of_club.svg",
        value: "02",
        type: "club",
    },
    {
        name : "three of Club",
        link : "./img/cardDeck/Club/3_of_club.svg",
        value: "03",
        type: "club",
    },
    {
        name : "Four of Club",
        link : "./img/cardDeck/Club/4_of_club.svg",
        value: "04",
        type: "club",
    },
    {
        name : "Five of Club",
        link : "./img/cardDeck/Club/5_of_club.svg",
        value: "05",
        type: "club",
    },
    {
        name : "Six of Club",
        link : "./img/cardDeck/Club/6_of_club.svg",
        value: "06",
        type: "club",
    },
    {
        name : "Seven of Club",
        link : "./img/cardDeck/Club/7_of_club.svg",
        value: "07",
        type: "club",
    },
    {
        name : "Eight of Club",
        link : "./img/cardDeck/Club/8_of_club.svg",
        value: "08",
        type: "club",
    },
    {
        name : "Nine of Club",
        link : "./img/cardDeck/Club/9_of_club.svg",
        value: "09",
        type: "club",
    },
    {
        name : "Ten of Club",
        link : "./img/cardDeck/Club/10_of_club.svg",
        value: "10",
        type: "club",
    },
    {
        name : "Jack of Club",
        link : "./img/cardDeck/Club/J_of_club.svg",
        value: "11",
        type: "club",
    },
    {
        name : "Queen of Club",
        link : "./img/cardDeck/Club/Q_of_club.svg",
        value: "12",
        type: "club",
    },
    {
        name : "King of Club",
        link : "./img/cardDeck/Club/K_of_club.svg",
        value: "13",
        type: "club",
    },
    {
        name : "Ace of Club",
        link : "./img/cardDeck/Club/A_of_club.svg",
        value: "14",
        type: "club",
    },
    // Diamonds
    {
        name : "Two of Diamond",
        link : "./img/cardDeck/Diamond/2_of_diamond.svg",
        value: "02",
        type: "diamonds",
    },
    {
        name : "Three of Diamond",
        link : "./img/cardDeck/Diamond/3_of_diamond.svg",
        value: "03",
        type: "diamonds",
    },
    {
        name : "Four of Diamond",
        link : "./img/cardDeck/Diamond/4_of_diamond.svg",
        value: "04",
        type: "diamonds",
    },
    {
        name : "Five of Diamond",
        link : "./img/cardDeck/Diamond/5_of_diamond.svg",
        value: "05",
        type: "diamonds",
    },
    {
        name : "Six of Diamond",
        link : "./img/cardDeck/Diamond/6_of_diamond.svg",
        value: "06",
        type: "diamonds",
    },
    {
        name : "Seven of Diamond",
        link : "./img/cardDeck/Diamond/7_of_diamond.svg",
        value: "07",
        type: "diamonds",
    },
    {
        name : "Eight of Diamond",
        link : "./img/cardDeck/Diamond/8_of_diamond.svg",
        value: "08",
        type: "diamonds",
    },
    {
        name : "Nine of Diamond",
        link : "./img/cardDeck/Diamond/9_of_diamond.svg",
        value: "09",
        type: "diamonds",
    },
    {
        name : "Ten of Diamond",
        link : "./img/cardDeck/Diamond/10_of_diamond.svg",
        value: "10",
        type: "diamonds",
    },
    {
        name : "Jack of Diamond",
        link : "./img/cardDeck/Diamond/J_of_diamond.svg",
        value: "11",
        type: "diamonds",
    },
    {
        name : "Queen of Diamond",
        link : "./img/cardDeck/Diamond/Q_of_diamond.svg",
        value: "12",
        type: "diamonds",
    },
    {
        name : "King of Diamond",
        link : "./img/cardDeck/Diamond/K_of_diamond.svg",
        value: "13",
        type: "diamonds",
    },
    {
        name : "Ace of Diamond",
        link : "./img/cardDeck/Diamond/A_of_diamond.svg",
        value: "14",
        type: "diamonds",
    },
    // Hearts
    {
        name : "Two of Heart",
        link : "./img/cardDeck/Heart/2_of_heart.svg",
        value: "02",
        type: "heart",
    },
    {
        name : "Three of Heart",
        link : "./img/cardDeck/Heart/3_of_heart.svg",
        value: "03",
        type: "heart",
    },
    {
        name : "Four of Heart",
        link : "./img/cardDeck/Heart/4_of_heart.svg",
        value: "04",
        type: "heart",
    },
    {
        name : "Five of Heart",
        link : "./img/cardDeck/Heart/5_of_heart.svg",
        value: "05",
        type: "heart",
    },
    {
        name : "Six of Heart",
        link : "./img/cardDeck/Heart/6_of_heart.svg",
        value: "06",
        type: "heart",
    },
    {
        name : "Seven of Heart",
        link : "./img/cardDeck/Heart/7_of_heart.svg",
        value: "07",
        type: "heart",
    },
    {
        name : "Eight of Heart",
        link : "./img/cardDeck/Heart/8_of_heart.svg",
        value: "08",
        type: "heart",
    },
    {
        name : "Nine of Heart",
        link : "./img/cardDeck/Heart/9_of_heart.svg",
        value: "09",
        type: "heart",
    },
    {
        name : "Ten of Heart",
        link : "./img/cardDeck/Heart/10_of_heart.svg",
        value: "10",
        type: "heart",
    },
    {
        name : "Jack of Heart",
        link : "./img/cardDeck/Heart/J_of_heart.svg",
        value: "11",
        type: "heart",
    },
    {
        name : "Queen of Heart",
        link : "./img/cardDeck/Heart/Q_of_heart.svg",
        value: "12",
        type: "heart",
    },
    {
        name : "King of Heart",
        link : "./img/cardDeck/Heart/K_of_heart.svg",
        value: "13",
        type: "heart",
    },
    {
        name : "Ace of Heart",
        link : "./img/cardDeck/Heart/A_of_heart.svg",
        value: "14",
        type: "heart",
    },
    // Spades
    {
        name : "Two of Spade",
        link : "./img/cardDeck/Spade/2_of_spade.svg",
        value: "02",
        type: "spade",
    },
    {
        name : "Three of Spade",
        link : "./img/cardDeck/Spade/3_of_spade.svg",
        value: "03",
        type: "spade",
    },
    {
        name : "Four of Spade",
        link : "./img/cardDeck/Spade/4_of_spade.svg",
        value: "04",
        type: "spade",
    },
    {
        name : "Five of Spade",
        link : "./img/cardDeck/Spade/5_of_spade.svg",
        value: "05",
        type: "spade",
    },
    {
        name : "Six of Spade",
        link : "./img/cardDeck/Spade/6_of_spade.svg",
        value: "06",
        type: "spade",
    },
    {
        name : "Seven of Spade",
        link : "./img/cardDeck/Spade/7_of_spade.svg",
        value: "07",
        type: "spade",
    },
    {
        name : "Eight of Spade",
        link : "./img/cardDeck/Spade/8_of_spade.svg",
        value: "08",
        type: "spade",
    },
    {
        name : "Nine of Spade",
        link : "./img/cardDeck/Spade/9_of_spade.svg",
        value: "09",
        type: "spade",
    },
    {
        name : "Ten of Spade",
        link : "./img/cardDeck/Spade/10_of_spade.svg",
        value: "10",
        type: "spade",
    },
    {
        name : "Jack of Spade",
        link : "./img/cardDeck/Spade/J_of_spade.svg",
        value: "11",
        type: "spade",
    },
    {
        name : "Queen of Spade",
        link : "./img/cardDeck/Spade/Q_of_spade.svg",
        value: "12",
        type: "spade",
    },
    {
        name : "King of Spade",
        link : "./img/cardDeck/Spade/K_of_spade.svg",
        value: "13",
        type: "spade",
    },
    {
        name : "Ace of Spade",
        link : "./img/cardDeck/Spade/A_of_spade.svg",
        value: "14",
        type: "spade",
    },
];